version: '2'

volumes:
  display-socket:                    # Shared Wayland runtime directory
  settings:                          # Only required if using PERSISTENT flag (see below)
  my-data:

services:

  display:
    build: ./display
    privileged: true
    volumes:
      - display-socket:/run
    labels:
      io.balena.features.dbus: '1'
      
  browser:
    build: .
    privileged: true # required for sound (/dev/snd) and V4L2 video-decode (/dev/video*) device access
    depends_on:
      - display
    environment:
      XDG_RUNTIME_DIR: /run/user/0
      WAYLAND_DISPLAY: wayland-0
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '5011:5011' # management API
    volumes:
      - display-socket:/run
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
    
  webserver:
    build: ./webserver
    ports:
      - "80:80"
    volumes:
      -  'my-data:/data/my-data'

  big-sensor:
    #image: bh.cr/al_s_apps/big-sensor-armv7hf
    build: ./big-sensor
    restart: always
    labels:
      io.balena.features.supervisor-api: 1  # necessary to discover services
    privileged: true # necessary to read sensors

  signage:
    build: ./signage
    restart: always
    volumes:
      -  'my-data:/data/my-data'
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
      
  simple:
    build: ./simple
    restart: always
    volumes:
      -  'my-data:/data/my-data'
    privileged: true

      
