FROM ubuntu:jammy-20240227

# Don't prompt with any configuration questions
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /usr/src/app

RUN apt update && apt install -y git nano python3 curl python3-pip

RUN pip3 install requests

COPY *.py ./

cmd ["sleep", "infinity"]
